name: Your Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'Documentation/**'

jobs:
  test-action:
    uses: mai-space/action-typo3-documentation-on-github/.github/workflows/build.yml@main
    with:
      publish_dir: Documentation-GENERATED-temp/Result/project/0.0.0
    secrets: inherit
